/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:849630:
  appc.background(230);
} //_CODE_:window1:849630:

public void reset_click(GButton source, GEvent event) {  // resets all values
  sim.par.clear();
  sim.compression_change(0);
  sim.temperature_change(0);
  numpar.setValue(0);
  vol.setValue(0);
  temp.setValue(0);
} //_CODE_:reset:229217:

public void temp_change(GSlider source, GEvent event) { // changes the temperature 
  sim.temperature_change(temp.getValueF());
} //_CODE_:temp:995908:

public void vol_change(GSlider source, GEvent event) {  // changes the volume
  sim.compression_change(vol.getValueF());
} //_CODE_:vol:967372:

public void numpar_change(GSlider source, GEvent event) {  // changes the nummber of particles
  sim.add_particles(numpar.getValueI());
  sim.temperature_change(temp.getValueF());
} //_CODE_:numpar:733664:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 300, 250, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(window1, 10, 30, 80, 30);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Number of Particles");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 10, 90, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Temperature");
  label2.setOpaque(false);
  label3 = new GLabel(window1, 10, 140, 110, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Compression (%)");
  label3.setOpaque(false);
  numpar = new GSlider(window1, 125, 25, 150, 50, 10.0);
  numpar.setShowValue(true);
  numpar.setLimits(0, 0, 100);
  numpar.setNbrTicks(10);
  numpar.setShowTicks(true);
  numpar.setNumberFormat(G4P.INTEGER, 0);
  numpar.setOpaque(false);
  numpar.addEventHandler(this, "numpar_change");
  temp = new GSlider(window1, 125, 75, 150, 50, 10.0);
  temp.setShowValue(true);
  temp.setLimits(0.0, 0.0, 100.0);
  temp.setNbrTicks(10);
  temp.setShowTicks(true);
  temp.setNumberFormat(G4P.DECIMAL, 2);
  temp.setOpaque(false);
  temp.addEventHandler(this, "temp_change");
  vol = new GSlider(window1, 125, 125, 150, 50, 10.0);
  vol.setShowValue(true);
  vol.setLimits(0.0, 0.0, 100.0);
  vol.setNbrTicks(10);
  vol.setShowTicks(true);
  vol.setNumberFormat(G4P.DECIMAL, 2);
  vol.setOpaque(false);
  vol.addEventHandler(this, "vol_change");
  reset = new GButton(window1, 10, 180, 80, 30);
  reset.setText("Reset");
  reset.addEventHandler(this, "reset_click");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GLabel label1; 
GLabel label2; 
GLabel label3; 
GSlider numpar; 
GSlider temp; 
GSlider vol; 
GButton reset; 
